name: activv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  badges: ^3.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  iconfont: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/3d_avatar_13.png
    - assets/3d_avatar_22.png

  fonts:
    - family: Barlow-Bold
      fonts:
        - asset: fonts/Barlow-Bold.ttf

    - family: Inter-Var
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf

    